name: Update status

# Controls when the workflow will run
on:
  schedule:
    - cron: "19 * * * *"

  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Setup env vars
        run: |
          touch .env
          echo appKey=${{ secrets.APPKEY }} >> .env
          echo appSecret=${{ secrets.APPSECRET }} >> .env
          echo accessToken=${{ secrets.ACCESSTOKEN }} >> .env
          echo accessSecret=${{ secrets.ACCESSSECRET }} >> .env
          
      # Runs a single command using the runners shell
      - name: Install & run
        run: npm i && node index.js
